### ISSUE TITLE
after docker_compose   build ,  grafana is not starting - getsockopt: connection refused to postgres

### ISSUE THREAD

**Issue by thecreed** [distributed-system-analysis/sarjitsu#34] opened 2017-01-31 05:40 UTC
from journalctl in grafana container:
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: 2017/01/31 05:18:47 [I] Starting Grafana
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: 2017/01/31 05:18:47 [I] Version: 3.0.1, Commit: v3.0.1+2-g549eb15, Build date: 2016-05-11 08:37:21 +0000 UTC
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: 2017/01/31 05:18:47 [I] Configuration Info
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: Config files:
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: [0]: /usr/share/grafana/conf/defaults.ini
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: [1]: /etc/grafana/grafana.ini
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: Command lines overrides:
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: [0]: default.paths.data=/var/lib/grafana
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: [1]: default.paths.logs=/var/log/grafana
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: [2]: default.paths.plugins=/var/lib/grafana/plugins
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: Paths:
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: home: /usr/share/grafana
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: data: /var/lib/grafana
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: logs: /var/log/grafana
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: plugins: /var/lib/grafana/plugins
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: 2017/01/31 05:18:47 [I] Database: postgres
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: 2017/01/31 05:18:47 [I] Migrator: Starting DB migration
Jan 31 05:18:47 42b6e1a04058 grafana-server[193]: 2017/01/31 05:18:47 [log.go:84 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: dial tcp 172.18.0.2:5432: getsockopt: connection refused
Jan 31 05:18:47 42b6e1a04058 systemd[1]: grafana-server.service: Main process exited, code=exited, status=1/FAILURE
Jan 31 05:18:47 42b6e1a04058 systemd[1]: grafana-server.service: Unit entered failed state.
Jan 31 05:18:47 42b6e1a04058 systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Jan 31 05:18:47 42b6e1a04058 systemd[1]: grafana-server.service: Service hold-off time over, scheduling restart.
Jan 31 05:18:47 42b6e1a04058 systemd[1]: grafana-server.service: Start request repeated too quickly.
Jan 31 05:18:47 42b6e1a04058 systemd[1]: Failed to start Starts and stops a single grafana instance on this system.
red failed state.2b6e1a04058 systemd[1]: grafana-server.service: Unit ente--More--
Jan 31 05:18:47 42b6e1a04058 systemd[1]: grafana-server.service: Failed with result 'start-limit'.

this solved the issue:
[root@42b6e1a04058 /]# systemctl restart grafana-server
[root@42b6e1a04058 /]# systemctl status grafana-server
● grafana-server.service - Starts and stops a single grafana instance on this system
   Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-01-31 05:34:12 UTC; 6s ago
     Docs: http://docs.grafana.org
 Main PID: 302 (grafana-server)
   CGroup: /docker/42b6e1a0405807117096baae4266034577397bd836904e4667051a34eea4dc02/system.slice/grafana-server.service
           └─302 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile= cfg:default.paths.l...

Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [I] Migrator: exec migration id: ... v2
Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [I] Migrator: exec migration id: ... v2
Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [I] Migrator: exec migration id: ... v3
Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [I] Migrator: exec migration id: ... v3
Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [I] Created default admin user: admin
Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [I] Plugins: Scan starting
Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [W] Plugins: Plugin dir /var/lib/...ist
Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [I] Plugins: Plugin dir /var/lib/...ted
Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [T] Checking for updates
Jan 31 05:34:13 42b6e1a04058 grafana-server[302]: 2017/01/31 05:34:13 [I] Listen: http://0.0.0.0:3000
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by arcolife** [comment] 2017-02-01 06:57
@thecreed okay wow. I didn't face this issue. Is this reproducible on your end? I know one more guy who just ran this independently with success. Could this be a unique race condition issue? 

I had already added 'depends_on' for `frontend` service https://github.com/distributed-system-analysis/sarjitsu/blob/master/docker-compose.yml#L46 but I guess that doesn't cut it, if this is reproducible? 
edit: even if it's not, it worries me, as this might pop up some time again in future, without warning.

**Comment by arcolife** [comment] 2017-02-01 07:02
I guess it could be solved by adding a check on postgres liveliness in docker-entrypoint for frontend service. 

This was one of the reasons I planned to add support for OpenShift / k8s, as they have a hook for 'liveliness probe' on this stuff, IIRC.

**Comment by arcolife** [comment] 2017-02-03 05:44
fixed in https://github.com/distributed-system-analysis/sarjitsu/commit/b82108db811c5ad8493d86e842311234a3527818#diff-834d52d0e029a857766add9a6e8df81dR20

**Closed as completed by arcolife** 2017-02-03 05:44 UTC
